Repository 100-hours-a-week/22-tenten-be, pull requests merged in 2025-05, with the labels that each got.

#14 [FEAT] Post 도메인 엔티티, 레포지토리 완성
  src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostImage.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostImageRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/controller/S3Controller.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/exception/S3ErrorCode.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/exception/S3Exception.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
Labels: FEAT, REFACTOR, BE

#19 Feature/#18 authentication bug fix
  src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostLike.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostLikeService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/controller/S3Controller.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
  src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: FIX, BE

#20 [FEAT] 게시글 CRUD구현
  build.gradle
  src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
  src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetails.java
  src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
  src/main/java/com/kakaobase/snsapp/domain/members/repository/MemberRepository.java
  src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostLike.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostErrorCode.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostException.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostLikeService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/controller/S3Controller.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
  src/main/java/com/kakaobase/snsapp/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
  src/main/java/com/kakaobase/snsapp/global/security/SecurityUtil.java
  src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
  src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: FEAT, BE

#21 Feature/#10 post domain
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
  src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetails.java
  src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
  src/main/java/com/kakaobase/snsapp/domain/members/repository/MemberRepository.java
  src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostImage.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostLike.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostErrorCode.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostException.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostImageRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostLikeService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/controller/S3Controller.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/dto/PresignedUrlRequestDto.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/dto/PresignedUrlResponseDto.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/exception/S3ErrorCode.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/exception/S3Exception.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
  src/main/java/com/kakaobase/snsapp/global/config/AwsS3Config.java
  src/main/java/com/kakaobase/snsapp/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
  src/main/java/com/kakaobase/snsapp/global/security/SecurityUtil.java
  src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
  src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: FEAT, BE

#23 [BE-FEAT] Comment-Domain구현
  src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetails.java
  src/main/java/com/kakaobase/snsapp/domain/auth/principal/CustomUserDetailsService.java
  src/main/java/com/kakaobase/snsapp/domain/auth/service/UserAuthenticationService.java
  src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
  src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
  src/main/java/com/kakaobase/snsapp/domain/comments/converter/LikeConverter.java
  src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/CommentLike.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/Recomment.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/RecommentLike.java
  src/main/java/com/kakaobase/snsapp/domain/comments/exception/CommentErrorCode.java
  src/main/java/com/kakaobase/snsapp/domain/comments/exception/CommentException.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
Labels: FEAT, REFACTOR, BE

#25 [BE - FEAT] Comment도메인 서비스 로직 구현
  src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
  src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
  src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
  src/main/java/com/kakaobase/snsapp/domain/comments/exception/CommentErrorCode.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentLikeRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentLikeService.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
  src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
Labels: FEAT, BE

#27 [BE - FEAT] 유튜브 요약 기능 추가
  build.gradle
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/YouTubeSummaryService.java
  src/main/java/com/kakaobase/snsapp/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: FEAT, BE

#29 [BE - FEAT] 소셜봇 구현
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/BotRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
  src/main/java/com/kakaobase/snsapp/domain/posts/event/PostCounter.java
  src/main/java/com/kakaobase/snsapp/domain/posts/event/PostCreatedEvent.java
  src/main/java/com/kakaobase/snsapp/domain/posts/event/PostEventListener.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/global/common/constant/BotConstants.java
  src/main/java/com/kakaobase/snsapp/global/config/AsyncConfig.java
Labels: FEAT, BE

#31 [BE - FEAT] 소셜봇 대댓글 기능 구현
  src/main/java/com/kakaobase/snsapp/domain/comments/converter/BotRecommentConverter.java
  src/main/java/com/kakaobase/snsapp/domain/comments/dto/BotRecommentRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/comments/event/CommentCreatedEvent.java
  src/main/java/com/kakaobase/snsapp/domain/comments/event/CommentEventListener.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/BotRecommentService.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
  src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
Labels: FEAT, BE

#33 [FIX] 로그인이 회원의 닉네임 기수를 반환하도록 수정
  src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
  src/main/java/com/kakaobase/snsapp/domain/auth/dto/AuthResponseDto.java
Labels: FIX, BE

#35 [BE - REFACTOR] 코드리팩토링
  src/main/java/com/kakaobase/snsapp/domain/auth/service/UserAuthenticationService.java
  src/main/java/com/kakaobase/snsapp/domain/comments/controller/CommentController.java
  src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/Comment.java
  src/main/java/com/kakaobase/snsapp/domain/comments/entity/Recomment.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentLikeService.java
  src/main/java/com/kakaobase/snsapp/domain/members/converter/MemberConverter.java
  src/main/java/com/kakaobase/snsapp/domain/members/entity/Member.java
  src/main/java/com/kakaobase/snsapp/domain/posts/controller/PostController.java
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/PostImage.java
  src/main/java/com/kakaobase/snsapp/domain/posts/repository/PostImageRepository.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostLikeService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/dto/PresignedUrlResponseDto.java
  src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
  src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
  src/main/java/com/kakaobase/snsapp/global/security/SecurityUtil.java
Labels: FIX, REFACTOR, BE

#37 [BE - FEAT] 로그아웃시 revoked_refresh_tokens토큰값을 갱신하도록 수정
  src/main/java/com/kakaobase/snsapp/domain/auth/controller/AuthController.java
  src/main/java/com/kakaobase/snsapp/domain/auth/converter/AuthConverter.java
  src/main/java/com/kakaobase/snsapp/domain/auth/entity/RevokedRefreshToken.java
  src/main/java/com/kakaobase/snsapp/domain/auth/service/UserAuthenticationService.java
  src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
  src/main/resources/application.yml
Labels: FIX, BE

#47 Feature/#46 bot post detail fix
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: 버그-일반, FIX, BE

#49 Feature/#48 addrecomment count to response
  src/main/java/com/kakaobase/snsapp/domain/comments/converter/CommentConverter.java
  src/main/java/com/kakaobase/snsapp/domain/comments/dto/CommentResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
Labels: FIX, BE

#53 [CHORE] Cors 설정에 kakaobase도메인추가, 개발용 프론트엔드 ip추가
  src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
Labels: CHORE, BE

#66 Chore/#65 add cors www
  src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
Labels: CHORE, BE

#68 Fix /#67 fix comment time
  src/main/java/com/kakaobase/snsapp/Application.java
  src/main/resources/application.yml
Labels: FIX, BE

#72 [BE - FIX] 소셜봇 작성 요청에 소셜봇 게시글 필터링
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/BotRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
Labels: FIX, BE

#76 [BE - FIX] 댓글, 대댓글을 작성순으로 반환하도록 수정
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/CommentRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/repository/RecommentRepository.java
  src/main/java/com/kakaobase/snsapp/domain/comments/service/CommentService.java
Labels: FIX, BE

#78 Feat/#77 rate limit
  build.gradle
  src/main/java/com/kakaobase/snsapp/global/config/WebMvcConfig.java
  src/main/java/com/kakaobase/snsapp/global/interceptor/AiRateLimitInterceptor.java
  src/main/java/com/kakaobase/snsapp/global/interceptor/GlobalRateLimitInterceptor.java
  src/main/java/com/kakaobase/snsapp/global/util/BucketUtils.java
Labels: FEAT, BE

#80 [FIX] 소셜봇 게시글 필터 로직을 수정
  src/main/java/com/kakaobase/snsapp/domain/posts/service/BotPostService.java
Labels: FIX, BE

#83 [BE - !HOTFIX] 유튜브 요약을 비동기처리
  src/main/java/com/kakaobase/snsapp/domain/auth/dto/AuthResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/auth/service/UserAuthenticationService.java
  src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberResponseDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/dto/PostRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/entity/Post.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostErrorCode.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/YoutubeSummaryStatus.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/PostService.java
  src/main/java/com/kakaobase/snsapp/domain/posts/service/YouTubeSummaryService.java
  src/main/java/com/kakaobase/snsapp/global/error/exception/AiServerException.java
  src/main/java/com/kakaobase/snsapp/global/error/handler/WebClientErrorHandler.java
Labels: !HOTFIX, BE

#89 Hotfix/#88 error code fix
  src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/PostErrorCode.java
  src/main/java/com/kakaobase/snsapp/domain/posts/exception/YoutubeSummaryStatus.java
Labels: !HOTFIX, BE

#113 [BE - !HOTFIX] 배포 서버의 로그를 디스코드 웹훅으로 전송
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/console-appender.xml
  src/main/resources/discord-error-appender.xml
  src/main/resources/logback-spring.xml
Labels: !HOTFIX

#142 [BE - FIX] 이메일 인증시 401에러가뜨는 버그 수정
  src/main/java/com/kakaobase/snsapp/domain/posts/converter/PostConverter.java
  src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
  src/main/java/com/kakaobase/snsapp/global/security/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: FIX, BE

#145 [FIX] JwtFilter에 경로에 /api를 붙여 필터에서 제외되도록 설정
  src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
Labels: FIX, BE

#148 [CHORE] CORS에 https localhost추가
  src/main/java/com/kakaobase/snsapp/global/security/config/CorsConfig.java
Labels: !HOTFIX, BE

#149 Fix/#146 front 404 error
  src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: FIX, BE

#151 [BE - FIX] 게시글 목록조회시 403에러 수정 및 로컬전용 Context-path추가
  src/main/java/com/kakaobase/snsapp/global/security/AccessChecker.java
  src/main/java/com/kakaobase/snsapp/global/security/jwt/JwtAuthenticationFilter.java
Labels: BE

#161 [BE - FIX] S3 수동 설정 제거, 자동설정으로 전환
  src/main/java/com/kakaobase/snsapp/global/common/s3/service/S3Service.java
  src/main/java/com/kakaobase/snsapp/global/config/AwsS3Config.java
  src/main/resources/application.yml
Labels: FIX, BE

#164 [BE - FIX] MemberReqest에@JsonProperty추가
  src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
Labels: FIX, BE

#165 [BE - TEST] Member도메인 단위테스트 구현
  build.gradle
  src/test/java/com/kakaobase/snsapp/domain/auth/service/AuthServiceTest.java
  src/test/java/com/kakaobase/snsapp/domain/auth/service/SecurityTokenManagerTest.java
  src/test/java/com/kakaobase/snsapp/domain/members/service/EmailVerificationServiceTest.java
  src/test/java/com/kakaobase/snsapp/domain/members/service/MemberServiceTest.java
  src/test/java/com/kakaobase/snsapp/global/config/TestSecurityConfig.java
  src/test/java/com/kakaobase/snsapp/global/constants/MemberFixtureConstants.java
  src/test/java/com/kakaobase/snsapp/global/fixture/CustomUserDetailsFixture.java
  src/test/java/com/kakaobase/snsapp/global/fixture/MemberFixture.java
  src/test/java/com/kakaobase/snsapp/global/fixture/MemberRequestFixture.java
  src/test/java/com/kakaobase/snsapp/global/mock/builder/MockCustomUserDetailsBuilder.java
  src/test/java/com/kakaobase/snsapp/global/mock/builder/MockMemberBuilder.java
  src/test/java/com/kakaobase/snsapp/global/mock/constants/MockMemberConstants.java
Labels: TEST, BE

#172 [BE - FEAT] 비밀번호 수정 기능 구현
  src/main/java/com/kakaobase/snsapp/domain/members/controller/MemberController.java
  src/main/java/com/kakaobase/snsapp/domain/members/dto/MemberRequestDto.java
  src/main/java/com/kakaobase/snsapp/domain/members/service/MemberService.java
  src/main/java/com/kakaobase/snsapp/global/common/email/dto/EmailRequest.java
Labels: FEAT, BE
